databases:
  - name: altair
    databaseName: altair
    user: altair
    region: frankfurt
    plan: free

services:
  - type: web
    name: altair
    runtime: ruby
    region: frankfurt
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    ## TODO Advanced config - not working...
    #startCommand: "bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: altair
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: REDIS_URL
        fromService:
          type: redis
          name: altair-redis
          property: connectionString
  - type: redis
    name: altair-redis
    region: frankfurt
    plan: free
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections
