databases:
  - name: altair
    databaseName: altair
    user: altair
    plan: free

services:
  - type: web
    name: altair
    runtime: ruby
    plan: free
    buildCommand: "bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean;"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: altair
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: REDIS_URL
        value: redis://red-co8g2qev3ddc73fhc1rg:6379
